apiVersion: v2
name: kagent
description: A Helm chart for installing Kagent along with Ollama integration
type: application
version: 0.1.0
appVersion: "0.7.13"
dependencies:
  - name: kagent
    version: 0.7.13
    repository: oci://ghcr.io/kagent-dev/kagent/helm
  - name: ollama
    version: 1.41.0
    repository: https://helm.otwld.com/
